# Generated by Django 3.2.4 on 2021-06-09 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210609_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[('0', 'Cancelled'), ('1', 'Confirmed'), ('2', 'On Hold')], default='Confirmed'),
        ),
    ]
