# Generated by Django 3.2.4 on 2021-06-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210609_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[('0', 'Cancelled'), ('1', 'Confirmed'), ('2', 'On Hold')], default='1'),
        ),
    ]
